name: Labs Test

on: push

jobs:
  lab1:
    runs-on: ubuntu-16.04
    name: Lab №1
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm run test-lab-1
  lab2:
    runs-on: ubuntu-16.04
    name: Lab №2
    needs: [lab1]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm run test-lab-2
