name: Labs Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        labs: [ '1', '2' ]
    name: Lab# ${{ matrix.labs }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm run test-lab-${{ matrix.labs }}
